name: Cypress Frame Tests 
on: [push]
jobs: 
  cypress-run:
    runs-on: macos-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Write the cypress.env.json file from github secret
        run: |
          echo '${{ secrets.CYPRESS_ENV }}' > ./cypress.env.json
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with: 
          start: npm run test
          
